import type { ConditionCtx, ConditionDef } from '@ed/engine';

/**
 * Maux du corps et de l'esprit — pack « Le Rivage » (doc 12).
 *
 * Ce ne sont pas des étiquettes cliniques : ce sont des **processus**. Chacun
 * attaque des organes, déplace des constantes, évolue à sa vitesse et se voit
 * par des signes. Le nom est celui que le monde emploie — le Rivage médiéval
 * dit « la toux noire », pas « tuberculose ». Le champ `clinical` n'est là que
 * pour nous, et n'apparaît jamais à l'écran.
 *
 * Trois règles d'écriture :
 *  - un mal doit **changer une décision**, sinon il n'a rien à faire ici ;
 *  - un mal de l'esprit se joue comme un mal du corps : il évolue, il rémet,
 *    il n'est jamais un ressort comique ;
 *  - le poids d'apparition est petit. Un corps qui collectionne les maladies
 *    n'est pas une simulation, c'est une farce.
 */

const age = (c: ConditionCtx): number => c.age;
const poor = (c: ConditionCtx): boolean => c.subject.wealth < 250;
const dirty = (c: ConditionCtx): number =>
  (c.world.settlement(c.subject.settlement)?.danger ?? 30) / 100;
const crowded = (c: ConditionCtx): number => {
  const size = c.world.settlement(c.subject.settlement)?.size;
  return size === 'cité' ? 1 : size === 'ville' ? 0.8 : size === 'bourg' ? 0.5 : 0.25;
};
const weakImmune = (c: ConditionCtx): number => Math.max(0, (60 - c.body.organs.immunite) / 60);
const sad = (c: ConditionCtx): number => Math.max(0, (45 - c.subject.mood) / 45);

// ─── infections ──────────────────────────────────────────────────────────────

const INFECTIONS: ConditionDef[] = [
  {
    id: 'flux_ventre',
    label: 'le flux de ventre',
    clinical: 'dysenterie',
    kind: 'infection',
    course: 'aigu',
    onset: (c) => 0.9 * crowded(c) + (poor(c) ? 0.7 : 0) + dirty(c),
    drift: 9,
    remission: 0.55,
    organs: { digestif: 7, reins: 3, sang: 2 },
    vitals: { eau: -30, chaleur: 14 },
    infectious: 26,
    pain: 22,
    lethal: { above: 55, chance: 0.14 },
    signs: ['le teint gris', 'il ne garde plus rien', 'il se vide et ne se relève pas'],
    care: 7,
  },
  {
    id: 'fievre_marais',
    label: 'la fièvre des marais',
    clinical: 'paludisme',
    kind: 'infection',
    course: 'cyclique',
    onset: (c) => (c.subject.settlement === 'marches' || c.subject.settlement === 'orin' ? 1.2 : 0.15),
    drift: 3,
    remission: 0.3,
    organs: { sang: 4, foie: 3, immunite: 2 },
    vitals: { chaleur: 24, tension: -10 },
    infectious: 8,
    pain: 14,
    lethal: { above: 65, chance: 0.09 },
    marks: ['maladif'],
    signs: ['des accès de fièvre tous les trois jours', 'des tremblements qui reviennent', 'la fièvre le prend et le lâche depuis des années'],
    care: 5,
  },
  {
    id: 'toux_noire',
    label: 'la toux noire',
    clinical: 'tuberculose',
    kind: 'infection',
    course: 'lent',
    onset: (c) => 0.5 * crowded(c) + weakImmune(c) * 0.8 + (poor(c) ? 0.4 : 0),
    drift: 5,
    remission: 0.08,
    silentBelow: 22,
    organs: { poumons: 8, sang: 2, muscles: 3 },
    vitals: { souffle: -18, chaleur: 10 },
    infectious: 14,
    lethal: { above: 60, chance: 0.16 },
    marks: ['maladif'],
    signs: ['une toux qui ne le quitte plus', 'il crache du sang dans un linge', 'il n\'a plus que la peau'],
    care: 4,
  },
  {
    id: 'petite_verole',
    label: 'la petite vérole',
    clinical: 'variole',
    kind: 'infection',
    course: 'aigu',
    once: true,
    onset: (c) => (age(c) < 25 ? 0.7 : 0.2) * crowded(c),
    drift: 16,
    remission: 0.5,
    organs: { peau: 10, immunite: 5, sens: 4 },
    vitals: { chaleur: 30 },
    infectious: 34,
    pain: 30,
    lethal: { above: 50, chance: 0.22 },
    marks: ['marque'],
    signs: ['le visage couvert de pustules', 'on ne le reconnaît plus', 'il ne voit plus que des ombres'],
    care: 3,
  },
  {
    id: 'plaie_tourne',
    label: 'une plaie qui a tourné',
    clinical: 'septicémie',
    kind: 'infection',
    course: 'aigu',
    onset: (c) => (c.subject.injuries.length > 0 ? 0.9 : 0.1) + dirty(c) * 0.5,
    drift: 22,
    remission: 0.35,
    organs: { sang: 9, reins: 6, coeur: 5 },
    vitals: { chaleur: 34, pouls: 26, tension: -18 },
    infectious: 12,
    pain: 34,
    lethal: { above: 45, chance: 0.3 },
    signs: ['la plaie sent mauvais', 'des traînées rouges remontent le bras', 'il délire de fièvre'],
    care: 9,
  },
  {
    id: 'mal_poumons',
    label: 'le mal chaud des poumons',
    clinical: 'pneumonie',
    kind: 'infection',
    course: 'aigu',
    onset: (c) => 0.5 + (age(c) > 55 ? 1 : 0) + weakImmune(c),
    drift: 15,
    remission: 0.45,
    organs: { poumons: 10, coeur: 3 },
    vitals: { souffle: -26, chaleur: 22, pouls: 16 },
    infectious: 10,
    lethal: { above: 50, chance: 0.2 },
    signs: ['il respire court', 'chaque souffle siffle', 'il se noie assis'],
    care: 8,
  },
  {
    id: 'gorge_blanche',
    label: 'le mal de gorge blanc',
    clinical: 'diphtérie',
    kind: 'infection',
    course: 'aigu',
    once: true,
    onset: (c) => (age(c) < 14 ? 0.8 : 0.15) * crowded(c),
    drift: 20,
    remission: 0.4,
    organs: { poumons: 7, coeur: 6, nerfs: 3 },
    vitals: { souffle: -30, chaleur: 18 },
    infectious: 22,
    lethal: { above: 45, chance: 0.26 },
    signs: ['la gorge est tapissée de blanc', 'la voix s\'éteint', 'l\'air ne passe plus'],
    care: 6,
  },
  {
    id: 'fievre_couches',
    label: 'la fièvre des couches',
    clinical: 'fièvre puerpérale',
    kind: 'infection',
    course: 'aigu',
    onset: (c) =>
      c.subject.sex === 'f' && (c.subject.flags['accouchement_recent'] === true ? 1 : 0) ? 5 : 0,
    drift: 24,
    remission: 0.3,
    organs: { sang: 10, reins: 6 },
    vitals: { chaleur: 32, pouls: 24 },
    lethal: { above: 40, chance: 0.34 },
    signs: ['la fièvre est montée le troisième jour', 'elle ne reconnaît plus personne'],
    care: 8,
  },
  {
    id: 'peste',
    label: 'la peste',
    kind: 'infection',
    course: 'aigu',
    onset: (c) => (c.world.flags['peste'] === true ? 14 : 0),
    drift: 34,
    remission: 0.22,
    organs: { sang: 14, immunite: 10, poumons: 6 },
    vitals: { chaleur: 36, tension: -22 },
    infectious: 60,
    pain: 45,
    lethal: { above: 35, chance: 0.42 },
    signs: ['des bubons à l\'aine', 'la peau marbre de noir', 'il ne passera pas la nuit'],
    care: 3,
  },
  {
    id: 'suette',
    label: 'la suette',
    kind: 'infection',
    course: 'aigu',
    onset: (c) => 0.3 * crowded(c),
    drift: 26,
    remission: 0.6,
    organs: { coeur: 6, sang: 4 },
    vitals: { chaleur: 26, pouls: 22, eau: -24 },
    infectious: 20,
    lethal: { above: 55, chance: 0.18 },
    signs: ['il sue à tremper les draps', 'la sueur ne s\'arrête plus'],
    care: 5,
  },
];

// ─── maux installés ──────────────────────────────────────────────────────────

const CHRONIQUES: ConditionDef[] = [
  {
    id: 'mal_poitrine',
    label: 'le mal de poitrine',
    clinical: 'angine de poitrine',
    kind: 'chronique',
    course: 'lent',
    onset: (c) => (age(c) > 45 ? (age(c) - 45) * 0.05 : 0) + (c.body.vitals.tension > 62 ? 0.8 : 0),
    drift: 3,
    silentBelow: 18,
    organs: { coeur: 5 },
    vitals: { tension: 12, souffle: -8 },
    pain: 16,
    lethal: { above: 70, chance: 0.14 },
    signs: ['il s\'arrête en montant les marches', 'une main sur la poitrine, souvent', 'il ne sort plus'],
    care: 4,
  },
  {
    id: 'le_sucre',
    label: 'le mal du sucre',
    clinical: 'diabète',
    kind: 'chronique',
    course: 'lent',
    onset: (c) => (c.subject.wealth > 12000 && age(c) > 35 ? 0.7 : 0.12) + (age(c) > 50 ? 0.4 : 0),
    drift: 2.5,
    silentBelow: 20,
    organs: { reins: 5, sens: 4, nerfs: 4, peau: 3 },
    vitals: { sucre: 30, eau: -14 },
    lethal: { above: 80, chance: 0.1 },
    signs: ['une soif que rien ne calme', 'des plaies aux pieds qui ne ferment pas', 'il ne voit presque plus'],
    care: 3,
  },
  {
    id: 'mal_pierre',
    label: 'le mal de la pierre',
    clinical: 'lithiase',
    kind: 'chronique',
    course: 'cyclique',
    onset: (c) => (age(c) > 30 ? 0.45 : 0.1),
    drift: 1.5,
    remission: 0.2,
    organs: { reins: 4 },
    pain: 40,
    lethal: { above: 85, chance: 0.07 },
    signs: ['des crises qui le plient en deux', 'il crie la nuit'],
    care: 5,
  },
  {
    id: 'goutte',
    label: 'la goutte',
    kind: 'chronique',
    course: 'cyclique',
    onset: (c) => (c.subject.wealth > 8000 && age(c) > 40 ? 0.9 : 0.08),
    drift: 1.8,
    remission: 0.25,
    organs: { os: 3, reins: 2 },
    pain: 28,
    signs: ['il boite après les banquets', 'le gros orteil rouge et brûlant', 'il ne peut plus mettre de botte'],
    care: 4,
  },
  {
    id: 'mal_caduc',
    label: 'le mal caduc',
    clinical: 'épilepsie',
    kind: 'chronique',
    course: 'cyclique',
    onset: (c) => (age(c) < 25 ? 0.35 : 0.12),
    drift: 0.8,
    remission: 0.06,
    organs: { cerveau: 2 },
    vitals: {},
    lethal: { above: 90, chance: 0.06 },
    marks: ['marque'],
    signs: ['il tombe parfois, sans prévenir', 'on le tient pour possédé', 'on l\'a chassé de trois maisons'],
    care: 2,
  },
  {
    id: 'oppression',
    label: 'l\'oppression',
    clinical: 'asthme',
    kind: 'chronique',
    course: 'cyclique',
    onset: (c) => (age(c) < 16 ? 0.5 : 0.15) + dirty(c) * 0.3,
    drift: 1.2,
    remission: 0.12,
    organs: { poumons: 3 },
    vitals: { souffle: -18 },
    lethal: { above: 88, chance: 0.06 },
    signs: ['il siffle en respirant', 'il ne peut plus courir', 'une crise peut l\'emporter'],
    care: 4,
  },
  {
    id: 'ulcere',
    label: 'le feu de l\'estomac',
    clinical: 'ulcère',
    kind: 'chronique',
    course: 'lent',
    onset: (c) => 0.3 + sad(c) * 0.6,
    drift: 2,
    remission: 0.18,
    organs: { digestif: 5, sang: 3 },
    pain: 24,
    lethal: { above: 80, chance: 0.1 },
    signs: ['il mange debout, à peine', 'du sang dans ce qu\'il rend'],
    care: 5,
  },
  {
    id: 'hydropisie',
    label: 'l\'hydropisie',
    clinical: 'insuffisance rénale ou cardiaque',
    kind: 'chronique',
    course: 'lent',
    onset: (c) => (age(c) > 50 ? 0.5 : 0.05) + (c.body.organs.reins < 55 ? 1 : 0),
    drift: 3.5,
    organs: { reins: 6, coeur: 4 },
    vitals: { eau: 30, tension: 14 },
    lethal: { above: 65, chance: 0.16 },
    signs: ['les jambes gonflent', 'le ventre se remplit d\'eau', 'il dort assis pour respirer'],
    care: 3,
  },
];

// ─── ce qui use ──────────────────────────────────────────────────────────────

const DEGENERATIFS: ConditionDef[] = [
  {
    id: 'rouille',
    label: 'la rouille des articulations',
    clinical: 'arthrose',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 42 ? (age(c) - 42) * 0.09 : 0),
    drift: 2.2,
    organs: { os: 3, muscles: 2 },
    pain: 20,
    signs: ['les mains se ferment mal le matin', 'il ne monte plus à cheval', 'chaque geste lui coûte'],
    care: 3,
  },
  {
    id: 'os_creux',
    label: 'les os creux',
    clinical: 'ostéoporose',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 55 ? (age(c) - 55) * 0.1 * (c.subject.sex === 'f' ? 1.6 : 1) : 0),
    drift: 2.4,
    organs: { os: 6 },
    lethal: { above: 85, chance: 0.08 },
    signs: ['il s\'est cassé le poignet en trébuchant', 'le dos se voûte', 'une chute et c\'est la hanche'],
    care: 2,
  },
  {
    id: 'vue_qui_part',
    label: 'la vue qui s\'en va',
    clinical: 'cataracte',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 50 ? (age(c) - 50) * 0.13 : 0),
    drift: 3,
    organs: { sens: 7 },
    marks: ['aveugle'],
    signs: ['il approche les choses de son visage', 'un voile blanc sur l\'œil', 'il ne distingue plus les visages'],
    care: 2,
  },
  {
    id: 'oreille_fermee',
    label: 'l\'oreille qui se ferme',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 48 ? (age(c) - 48) * 0.1 : 0) + (c.subject.jobId === 'forgeron' ? 0.8 : 0),
    drift: 2.6,
    organs: { sens: 5 },
    marks: ['sourd'],
    signs: ['il fait répéter', 'il parle trop fort', 'il n\'entend plus rien'],
    care: 1,
  },
  {
    id: 'tremblement',
    label: 'le tremblement',
    clinical: 'syndrome parkinsonien',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 55 ? (age(c) - 55) * 0.06 : 0),
    drift: 3.2,
    organs: { nerfs: 6, muscles: 4, cerveau: 2 },
    lethal: { above: 90, chance: 0.08 },
    signs: ['la main gauche tremble au repos', 'il renverse ce qu\'il porte', 'il ne peut plus se nourrir seul'],
    care: 2,
  },
  {
    id: 'oubli',
    label: 'l\'oubli',
    clinical: 'démence',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 62 ? (age(c) - 62) * 0.11 : 0),
    drift: 3.4,
    silentBelow: 18,
    organs: { cerveau: 7 },
    lethal: { above: 88, chance: 0.12 },
    signs: ['il cherche ses mots', 'il ne sait plus quel jour on est', 'il ne reconnaît plus ses enfants'],
    care: 1,
  },
  {
    id: 'coeur_use',
    label: 'le cœur qui s\'épuise',
    clinical: 'insuffisance cardiaque',
    kind: 'degeneratif',
    course: 'lent',
    onset: (c) => (age(c) > 58 ? (age(c) - 58) * 0.1 : 0) + (c.body.organs.coeur < 55 ? 1.2 : 0),
    drift: 4,
    organs: { coeur: 7, poumons: 3, reins: 3 },
    vitals: { souffle: -16, pouls: 12 },
    lethal: { above: 55, chance: 0.2 },
    signs: ['il souffle en parlant', 'il ne traverse plus la cour', 'il attend assis'],
    care: 3,
  },
];

// ─── de naissance ────────────────────────────────────────────────────────────

const GENETIQUES: ConditionDef[] = [
  {
    id: 'sang_qui_fuit',
    label: 'le sang qui ne prend pas',
    clinical: 'hémophilie',
    kind: 'genetique',
    course: 'lent',
    onset: (c) => (age(c) <= 3 && c.subject.hidden.genetique < 32 ? 3 : 0),
    once: true,
    drift: 0.4,
    organs: { sang: 2 },
    lethal: { above: 60, chance: 0.09 },
    signs: ['il saigne longtemps d\'une coupure', 'des bleus énormes pour rien', 'une coupure peut le tuer'],
    care: 2,
  },
  {
    id: 'souffle_de_naissance',
    label: 'le souffle court de naissance',
    kind: 'genetique',
    course: 'lent',
    onset: (c) => (age(c) <= 2 && c.subject.hidden.genetique < 28 ? 2.5 : 0),
    once: true,
    drift: 1.6,
    organs: { poumons: 5, digestif: 2 },
    vitals: { souffle: -14 },
    lethal: { above: 70, chance: 0.14 },
    marks: ['maladif'],
    signs: ['il tousse depuis toujours', 'il ne grandit pas comme les autres'],
    care: 2,
  },
  {
    id: 'sang_pale',
    label: 'le sang pâle',
    clinical: 'anémie héréditaire',
    kind: 'genetique',
    course: 'lent',
    onset: (c) => (age(c) <= 6 && c.subject.hidden.genetique < 40 ? 1.5 : 0),
    once: true,
    drift: 0.9,
    organs: { sang: 4, coeur: 2 },
    vitals: { souffle: -10, pouls: 10 },
    marks: ['chetif'],
    signs: ['il est blanc comme un linge', 'il s\'évanouit debout'],
    care: 4,
  },
  {
    id: 'os_de_verre',
    label: 'les os de verre',
    kind: 'genetique',
    course: 'lent',
    onset: (c) => (age(c) <= 4 && c.subject.hidden.genetique < 24 ? 2 : 0),
    once: true,
    drift: 0.7,
    organs: { os: 5 },
    pain: 18,
    lethal: { above: 80, chance: 0.08 },
    marks: ['chetif'],
    signs: ['il s\'est cassé trois fois avant dix ans', 'on ne le laisse plus sortir'],
    care: 2,
  },
  {
    id: 'la_danse',
    label: 'la danse',
    clinical: 'chorée héréditaire',
    kind: 'genetique',
    course: 'lent',
    onset: (c) => (age(c) > 32 && age(c) < 48 && c.subject.hidden.genetique < 26 ? 1.4 : 0),
    once: true,
    drift: 3.6,
    organs: { cerveau: 6, nerfs: 6, muscles: 3 },
    lethal: { above: 80, chance: 0.16 },
    signs: ['des gestes qu\'il ne commande pas', 'il danse sans le vouloir', 'son père est mort ainsi'],
    care: 1,
  },
];

// ─── le manque ───────────────────────────────────────────────────────────────

const CARENCES: ConditionDef[] = [
  {
    id: 'mal_de_mer',
    label: 'le mal des gencives',
    clinical: 'scorbut',
    kind: 'carence',
    course: 'lent',
    onset: (c) => (c.subject.jobId === 'matelot' || c.subject.jobId === 'second' ? 1.6 : poor(c) ? 0.5 : 0),
    drift: 6,
    remission: 0.4,
    organs: { peau: 5, os: 4, sang: 3 },
    pain: 16,
    lethal: { above: 70, chance: 0.14 },
    signs: ['les gencives saignent', 'les dents bougent', 'les vieilles plaies se rouvrent'],
    care: 12,
  },
  {
    id: 'jambes_torses',
    label: 'les jambes torses',
    clinical: 'rachitisme',
    kind: 'carence',
    course: 'lent',
    onset: (c) => (age(c) < 10 && poor(c) ? 1.2 : 0),
    once: true,
    drift: 3,
    organs: { os: 6 },
    marks: ['boiteux'],
    signs: ['les jambes s\'arquent', 'il marche en canard'],
    care: 6,
  },
  {
    id: 'goitre',
    label: 'le goitre',
    kind: 'carence',
    course: 'lent',
    onset: (c) => (c.subject.settlement === 'orin' || c.subject.settlement === 'marches' ? 0.8 : 0.1),
    drift: 1.6,
    organs: { endocrine: 4 },
    signs: ['une boule au cou', 'le cou déformé', 'la voix change'],
    care: 5,
  },
  {
    id: 'cecite_nuit',
    label: 'la cécité du soir',
    clinical: 'héméralopie',
    kind: 'carence',
    course: 'lent',
    onset: (c) => (poor(c) ? 0.9 : 0.1),
    drift: 2,
    remission: 0.3,
    organs: { sens: 3 },
    signs: ['il ne sort plus après la tombée du jour'],
    care: 9,
  },
];

// ─── le poison ───────────────────────────────────────────────────────────────

const TOXIQUES: ConditionDef[] = [
  {
    id: 'mal_du_plomb',
    label: 'le mal du plomb',
    clinical: 'saturnisme',
    kind: 'toxique',
    course: 'lent',
    onset: (c) => (c.subject.jobId === 'forgeron' || c.subject.jobId === 'apprenti_forge' ? 0.9 : 0.15),
    drift: 2.4,
    silentBelow: 20,
    organs: { nerfs: 5, cerveau: 4, sang: 4, reins: 3 },
    pain: 12,
    lethal: { above: 82, chance: 0.1 },
    signs: ['des coliques et de l\'humeur noire', 'les mains tombent', 'il n\'a plus toute sa tête'],
    care: 5,
  },
  {
    id: 'poumon_noir',
    label: 'le poumon noir',
    kind: 'toxique',
    course: 'lent',
    onset: (c) => (c.subject.jobId === 'journalier' && dirty(c) > 0.5 ? 0.7 : 0.1),
    drift: 2.8,
    organs: { poumons: 7 },
    vitals: { souffle: -18 },
    lethal: { above: 70, chance: 0.14 },
    signs: ['il crache noir', 'chaque hiver le rapproche'],
    care: 2,
  },
  {
    id: 'ivrognerie',
    label: 'l\'ivrognerie',
    clinical: 'alcoolisme',
    kind: 'toxique',
    course: 'lent',
    onset: (c) => 0.35 + sad(c) * 1.4 + (c.subject.traits.includes('brise') ? 0.8 : 0),
    drift: 2.6,
    remission: 0.1,
    organs: { foie: 7, cerveau: 4, digestif: 4 },
    vitals: { tension: 12 },
    lethal: { above: 75, chance: 0.14 },
    marks: ['notoire'],
    signs: ['il boit avant midi', 'les mains tremblent au réveil', 'il a tout vendu pour boire'],
    care: 4,
  },
  {
    id: 'mal_du_vif_argent',
    label: 'le mal du vif-argent',
    clinical: 'hydrargyrisme',
    kind: 'toxique',
    course: 'lent',
    onset: (c) => (c.subject.jobId === 'medecin' || c.subject.jobId === 'herboriste' ? 0.5 : 0.05),
    drift: 2.2,
    organs: { cerveau: 6, nerfs: 5, reins: 3 },
    lethal: { above: 85, chance: 0.09 },
    signs: ['il s\'emporte pour rien', 'il parle seul en travaillant', 'plus personne ne le suit'],
    care: 4,
  },
];

// ─── l'esprit ────────────────────────────────────────────────────────────────

/**
 * Ces maux ne sont jamais un ressort comique et jamais une leçon. Ils
 * évoluent, ils rémettent, ils coûtent — comme les autres. Le monde
 * médiéval n'a pas de mot pour eux : il a un regard.
 */
const ESPRIT: ConditionDef[] = [
  {
    id: 'melancolie',
    label: 'la mélancolie noire',
    clinical: 'dépression',
    kind: 'esprit',
    course: 'cyclique',
    onset: (c) =>
      0.5 +
      sad(c) * 2.2 +
      (c.subject.traits.includes('endeuille') ? 1.4 : 0) +
      (c.subject.traits.includes('brise') ? 1.2 : 0),
    drift: 2.4,
    remission: 0.22,
    organs: { cerveau: 2, immunite: 2 },
    vitals: { sucre: -8 },
    lethal: { above: 88, chance: 0.06 },
    marks: ['brise'],
    signs: ['il ne sort plus de chez lui', 'il ne mange plus qu\'un jour sur deux', 'il ne se lève plus'],
    care: 6,
  },
  {
    id: 'angoisse',
    label: 'l\'angoisse',
    clinical: 'trouble anxieux',
    kind: 'esprit',
    course: 'cyclique',
    onset: (c) => 0.6 + sad(c) + (c.subject.traits.includes('mefiant') ? 0.6 : 0),
    drift: 1.6,
    remission: 0.3,
    vitals: { pouls: 14, souffle: 10 },
    organs: { digestif: 2 },
    signs: ['il sursaute pour rien', 'il ne dort plus', 'il ne peut plus traverser la place'],
    care: 7,
  },
  {
    id: 'fureur',
    label: 'la fureur et l\'abattement',
    clinical: 'trouble bipolaire',
    kind: 'esprit',
    course: 'cyclique',
    onset: (c) => (age(c) > 15 && age(c) < 40 ? 0.5 : 0.12) + (c.subject.hidden.folie > 40 ? 0.8 : 0),
    drift: 1.4,
    remission: 0.12,
    organs: { cerveau: 2 },
    lethal: { above: 90, chance: 0.06 },
    marks: ['notoire'],
    signs: [
      'des semaines où il ne dort pas et entreprend tout',
      'il donne tout puis ne se lève plus',
      'on ne sait jamais lequel on trouvera',
    ],
    care: 4,
  },
  {
    id: 'voix_maladie',
    label: 'les voix',
    clinical: 'trouble psychotique',
    kind: 'esprit',
    course: 'lent',
    onset: (c) =>
      (age(c) > 15 && age(c) < 32 ? 0.4 : 0.06) +
      (c.subject.traits.includes('voix') ? 1.6 : 0) +
      c.subject.hidden.folie / 90,
    drift: 1.8,
    remission: 0.1,
    organs: { cerveau: 3 },
    marks: ['hante'],
    signs: ['il parle à quelqu\'un qui n\'est pas là', 'il se méfie de tout le monde', 'on l\'a enfermé une fois'],
    care: 3,
  },
  {
    id: 'ame_epuisee',
    label: 'l\'âme épuisée',
    clinical: 'stress post-traumatique',
    kind: 'esprit',
    course: 'lent',
    onset: (c) =>
      (c.subject.traits.includes('guerrier') ? 1.2 : 0) +
      (c.subject.traits.includes('hante') ? 1.4 : 0) +
      (c.subject.traits.includes('endurci') ? 0.5 : 0),
    drift: 1.5,
    remission: 0.18,
    organs: { cerveau: 2 },
    vitals: { pouls: 10 },
    signs: ['il se réveille en criant', 'un bruit sec le jette au sol', 'il ne dort plus près d\'une porte'],
    care: 6,
  },
  {
    id: 'obsession',
    label: 'l\'obsession',
    clinical: 'trouble obsessionnel',
    kind: 'esprit',
    course: 'lent',
    onset: (c) => 0.3 + (c.subject.traits.includes('esprit_a_part') ? 0.9 : 0),
    drift: 1.2,
    remission: 0.16,
    signs: ['il compte ses pas', 'il revient trois fois vérifier la porte', 'sa journée n\'y suffit plus'],
    care: 5,
  },
  {
    id: 'peur_des_lieux',
    label: 'la peur des lieux',
    clinical: 'agoraphobie',
    kind: 'esprit',
    course: 'lent',
    onset: (c) => 0.25 + sad(c) * 0.8 + (c.subject.traits.includes('esprit_a_part') ? 0.6 : 0),
    drift: 1.6,
    remission: 0.2,
    signs: ['il évite le marché', 'il ne sort plus qu\'à l\'aube', 'il n\'a pas passé sa porte depuis un an'],
    care: 6,
  },
  {
    id: 'faim_qui_ment',
    label: 'la faim qui ment',
    clinical: 'trouble du comportement alimentaire',
    kind: 'esprit',
    course: 'lent',
    onset: (c) => (age(c) > 12 && age(c) < 30 ? 0.45 : 0.08) + sad(c) * 0.9,
    drift: 2,
    remission: 0.18,
    organs: { digestif: 4, os: 3, coeur: 3, endocrine: 3 },
    vitals: { sucre: -16 },
    lethal: { above: 80, chance: 0.12 },
    marks: ['chetif'],
    signs: ['il ne mange plus devant les autres', 'les os saillent', 'le cœur bat mal'],
    care: 5,
  },
];

export const CONDITIONS: ConditionDef[] = [
  ...INFECTIONS,
  ...CHRONIQUES,
  ...DEGENERATIFS,
  ...GENETIQUES,
  ...CARENCES,
  ...TOXIQUES,
  ...ESPRIT,
];
